
INSERT INTO smn_salud.smn_presupuesto
(
	smn_presupuesto_id,
	smn_documento_id,
	smn_entidades_rf,
	smn_sucursales_rf,
	smn_clase_auxiliar_rf,
	smn_auxiliar_rf,
	smn_clase_ord_rf,
	smn_auxiliar_ord_rf,
	smn_baremo_rf,
	smn_auxiliar_unidades_negocios_rf,
	smn_auxiliar_sucursales_rf,
	smn_auxiliar_areas_servicios_rf,
	smn_auxiliar_unidades_servicios_rf,
	pre_vigencia_hasta,
	smn_ordenes_medicas_id,
	pre_fecha_entrega,
	pre_monto_ml,
	pre_monto_ma,
	smn_estado_presupuesto_id,
	pre_idioma,
	pre_usuario,
	pre_fecha_registro,
	pre_hora,
	smn_contratante_id,
	pre_tipo--,
	--smn_patologia_id
)
VALUES
(
	${seq:currval@smn_salud.seq_smn_presupuesto},
	${fld:smn_documento_id},
	(select smn_salud.smn_documento.smn_entidades_rf from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id=${fld:smn_documento_id}),
	(select smn_salud.smn_documento.smn_sucursales_rf from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id=${fld:smn_documento_id}),
	(select smn_base.smn_auxiliar.smn_clase_auxiliar_rf from smn_base.smn_auxiliar where smn_base.smn_auxiliar.smn_auxiliar_id=${fld:smn_auxiliar}),
	${fld:smn_auxiliar},
	0,
	0,
	(select smn_salud.smn_contratante.smn_baremos_id from smn_salud.smn_contratante where smn_salud.smn_contratante.smn_contratante_id=${fld:smn_contratante_id}),
	0,
	0,
	0,
	0,
	{d '${def:date}'},
	0,
	{d '${def:date}'},
	0,
	0,
	1,
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:smn_contratante_id},
	'PA'--,
	--${fld:smn_patologia_id}
)