INSERT INTO smn_comercial.smn_pedido_cabecera
(
	smn_pedido_cabecera_id,
	smn_documento_id,
	pca_numero_pedido,
	smn_mov_caja_cabecera_id,
	smn_cliente_id,
	smn_usuario_rf,
	pca_descripcion,
	pca_fecha_requerida,
	smn_entidad_rf,
	smn_sucursal_rf,
	smn_area_servicio_rf,
	smn_unidad_servicio_rf,
	smn_centro_costo_rf,
	smn_centro_facturacion_id,
	smn_tipo_linea_comercial_id,
	smn_linea_comercial_id,
	pca_monto_pedido_ml,
	pca_monto_neto_ml,
	smn_moneda_rf,
	smn_tasa_rf,
	pca_monto_pedido_ma,
	pca_monto_neto_ma,
	pca_estatus,
	pca_estatus_pago,
	pca_fecha_vencimiento,
	pca_idioma,
	pca_usuario,
	pca_fecha_registro,
	pca_hora,
	smn_auxiliar_rf,
	smn_modulo_rf,
	smn_ingresos_rf
)
VALUES
(
	${seq:nextval@smn_comercial.seq_smn_pedido_cabecera},
	(select smn_salud.smn_documento.smn_documento_id from smn_salud.smn_ingresos
	inner join smn_salud.smn_documento on smn_salud.smn_documento.smn_documento_id = smn_salud.smn_ingresos.smn_documento_id
	inner join smn_base.smn_documentos_generales on smn_base.smn_documentos_generales.smn_documentos_generales_id = smn_salud.smn_documento.smn_documento_general_rf
	where smn_salud.smn_ingresos.smn_ingresos_id=${fld:id_ingreso} limit 1),
	${seq:nextval@smn_comercial.seq_smn_numero_pedido},
	0,
	(select smn_comercial.smn_cliente.smn_cliente_id from smn_comercial.smn_cliente WHERE smn_comercial.smn_cliente.smn_auxiliar_rf=(select smn_salud.smn_contratante.smn_auxiliar_rf from smn_salud.smn_contratante where smn_salud.smn_contratante.smn_contratante_id=${fld:smn_contratante_id})),
	(select smn_base.smn_usuarios.smn_usuarios_id from smn_base.smn_auxiliar inner join smn_base.smn_usuarios on smn_base.smn_usuarios.smn_auxiliar_rf = smn_base.smn_auxiliar.smn_auxiliar_id inner join smn_seguridad.s_user on smn_seguridad.s_user.user_id = smn_base.smn_usuarios.smn_user_rf where smn_seguridad.s_user.userlogin='${def:user}' limit 1),
	'Pedido Generado desde Emergencia',
	${fld:igs_fecha_registro},
	${fld:smn_entidad_rf},
	${fld:smn_sucursal_rf},
	${fld:smn_area_servicio_rf},
	${fld:smn_unidad_servicio_rf},
	(select case when smn_comercial.smn_centro_facturacion.smn_centro_costo_rf is null then 0 else smn_comercial.smn_centro_facturacion.smn_centro_costo_rf end as smn_centro_costo_rf from smn_comercial.smn_centro_facturacion where smn_comercial.smn_centro_facturacion.smn_entidades_rf=${fld:smn_entidad_rf} and smn_comercial.smn_centro_facturacion.smn_sucursales_rf=${fld:smn_sucursal_rf} and smn_comercial.smn_centro_facturacion.smn_areas_servicios_rf=${fld:smn_area_servicio_rf}),
	(select smn_comercial.smn_centro_facturacion.smn_centro_facturacion_id from smn_comercial.smn_centro_facturacion where smn_comercial.smn_centro_facturacion.smn_entidades_rf=${fld:smn_entidad_rf} and smn_comercial.smn_centro_facturacion.smn_sucursales_rf=${fld:smn_sucursal_rf} and smn_comercial.smn_centro_facturacion.smn_areas_servicios_rf=${fld:smn_area_servicio_rf}),
	(select case when smn_comercial.smn_linea_comercial.smn_tipo_linea_comercial_id is null then 0 else smn_comercial.smn_linea_comercial.smn_tipo_linea_comercial_id end as smn_tipo_linea_comercial_id from smn_comercial.smn_linea_comercial where smn_comercial.smn_linea_comercial.smn_linea_comercial_id=(select case when smn_comercial.smn_rel_centro_fac_linea.smn_linea_comercial_id is null then 0 else smn_comercial.smn_rel_centro_fac_linea.smn_linea_comercial_id end as smn_linea_comercial_id from smn_comercial.smn_centro_facturacion inner join smn_comercial.smn_rel_centro_fac_linea on smn_comercial.smn_rel_centro_fac_linea.smn_centro_facturacion_id = smn_comercial.smn_centro_facturacion.smn_centro_facturacion_id where smn_comercial.smn_centro_facturacion.smn_entidades_rf=${fld:smn_entidad_rf} and smn_comercial.smn_centro_facturacion.smn_sucursales_rf=${fld:smn_sucursal_rf} and smn_comercial.smn_centro_facturacion.smn_areas_servicios_rf=${fld:smn_area_servicio_rf})),
	(select case when smn_comercial.smn_rel_centro_fac_linea.smn_linea_comercial_id is null then 0 else smn_comercial.smn_rel_centro_fac_linea.smn_linea_comercial_id end as smn_linea_comercial_id from smn_comercial.smn_centro_facturacion inner join smn_comercial.smn_rel_centro_fac_linea on smn_comercial.smn_rel_centro_fac_linea.smn_centro_facturacion_id = smn_comercial.smn_centro_facturacion.smn_centro_facturacion_id where smn_comercial.smn_centro_facturacion.smn_entidades_rf=${fld:smn_entidad_rf} and smn_comercial.smn_centro_facturacion.smn_sucursales_rf=${fld:smn_sucursal_rf} and smn_comercial.smn_centro_facturacion.smn_areas_servicios_rf=${fld:smn_area_servicio_rf}),
	${fld:igs_monto_moneda_local},
	${fld:igs_monto_moneda_local},
	${fld:smn_moneda_rf},
	(select smn_salud.smn_ingreso_movimiento.smn_tasa_rf from smn_salud.smn_ingreso_movimiento where smn_salud.smn_ingreso_movimiento.smn_ingreso_id=${fld:smn_ingresos_id} limit 1),
	${fld:igs_monto_moneda_alterna},
	${fld:igs_monto_moneda_alterna},
	'PR',
	'PE',
	'${def:date}',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:smn_auxiliar_rf},
	(select smn_base.smn_modulos.smn_modulos_id from smn_base.smn_modulos where smn_base.smn_modulos.mod_codigo='SMN_ADM' limit 1),
	${fld:smn_ingresos_id}
) RETURNING smn_pedido_cabecera_id;
