INSERT INTO smn_comercial.smn_pedido_detalle
(
	smn_pedido_detalle_id,
	smn_pedido_cabecera_id,
	smn_mov_caja_cabecera_id,
	pde_naturaleza,
	smn_servicios_rf,
	smn_item_rf,
	smn_activo_fijo_rf,
	pde_cantidad_oferta,
	pde_cantidad_pedido,
	pde_cantidad_aprobada,
	pde_precio,
	pde_monto,
	smn_moneda_rf,
	smn_tasa_rf,
	pde_precio_moneda_alterna,
	pde_monto_moneda_alterna,
	pde_especificaciones_pedido,
	pde_estatus,
	pde_idioma,
	pde_usuario,
	pde_fecha_registro,
	pde_hora,
	pde_fecha_requerida
)
VALUES
(
	${seq:nextval@smn_comercial.seq_smn_pedido_detalle},
	${fld:smn_pedido_cabecera_id},
	0,
	'SE',	
	(case when ${fld:smn_servicios_rf} is null then 0 else ${fld:smn_servicios_rf} end),
	0,
	0,
	0,
	(case when ${fld:inm_cantidad} is null then 0 else ${fld:inm_cantidad} end),
	(case when ${fld:inm_cantidad} is null then 0 else ${fld:inm_cantidad} end),
	(case when ${fld:inm_precio_ml} is null then 0 else ${fld:inm_precio_ml} end),
	(case when ${fld:inm_monto_ml} is null then 0 else ${fld:inm_monto_ml} end),
	(case when ${fld:smn_moneda_rf} is null then 0 else ${fld:smn_moneda_rf} end),
	(case when ${fld:smn_tasa_rf} is null then 0 else ${fld:smn_tasa_rf} end),
	(case when ${fld:inm_precio_ma} is null then 0 else ${fld:inm_precio_ma} end),
	(case when ${fld:inm_monto_ma} is null then 0 else ${fld:inm_monto_ma} end),
	'${def:date}',
	'NP',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	{d '${def:date}'}
) RETURNING smn_pedido_detalle_id, smn_servicios_rf, ${fld:smn_ingresos_mov_id} as smn_ingresos_mov_id, ${fld:smn_pedido_cabecera_id} as smn_pedido_cabecera_id;
