INSERT INTO smn_salud.smn_ingreso_movimiento
(
	smn_ingresos_mov_id,
	smn_ingreso_id,
	smn_servicios_rf,
	smn_unidades_servicios_rf,
	smn_componente_rf,
	inm_accion,
	smn_tipo_consulta_rf,
	smn_grupo_prestador_servicio_rf,
	smn_prestador_servicio_rf,
	smn_motivos_id,
	smn_clase_auxiliar_rf,
	smn_auxiliar_rf,
	inm_ordenante_descripcion,
	smn_sintoma_id,
	inm_tipo_orden,
	inm_num_orden_medica,
	inm_estatus,
	inm_idioma,
	inm_usuario,
	inm_fecha_registro,
	inm_hora
)
VALUES
(
	${seq:nextval@smn_salud.seq_smn_ingreso_movimiento},
	${fld:smn_ingreso_id},
	${fld:smn_servicios_id},
	(select smn_unidades_servicios_id from smn_base.smn_unidades_servicios where smn_base.smn_unidades_servicios.smn_areas_servicios_id = ${fld:id_area} and smn_base.smn_unidades_servicios.uns_descripcion = 'Laboratorio'),
	${fld:smn_componente_rf},
	${fld:inm_accion},
	${fld:smn_tipo_consulta_rf},
	${fld:smn_grupo_prestador_servicio_rf},
	${fld:smn_prestador_servicio_rf},
	${fld:smn_motivos_id},
	${fld:smn_clase_auxiliar_rf},
	${fld:smn_auxiliar_rf},
	${fld:inm_ordenante_descripcion},
	${fld:smn_sintoma_id},
	${fld:inm_tipo_orden},
	${fld:inm_num_orden_medica},
	'AC',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)

