select
	smn_salud.smn_tipo_documento_afiliado.tdo_codigo,
	smn_salud.smn_tipo_documento_afiliado.tdo_descripcion,
	smn_salud.smn_tipo_documento_afiliado.tdo_idioma,
	smn_salud.smn_tipo_documento_afiliado.tdo_usuario,
	smn_salud.smn_tipo_documento_afiliado.tdo_fecha_registro,
	smn_salud.smn_tipo_documento_afiliado.tdo_hora

from 
	smn_salud.smn_tipo_documento_afiliado
