INSERT INTO smn_salud.smn_prestacion_servicio_medico_detalle
(
	smn_prestacion_servicio_medico_detalle_id,
	smn_prestacion_servicio_medico_cabecera_id,
	smn_mov_caja_detalle_id,
	smn_ingresos_mov_id,
	smn_unidades_servicios_rf,
	smn_almacen_rf,
	smn_servicios_rf,
	psd_tipo_componentes,
	smn_componentes_rf,
	smn_item_rf,
	smn_prestador_servicio_rf,
	psd_cantidad,
	psd_precio_propuesto_ml,
	psd_monto_propuesto_ml,
	smn_descuento_ml_rf,
	smn_moneda_rf,
	psd_precio_propuesto_ma,
	psd_monto_propuesto_ma,
	psd_monto_descuento_propuesto_ml,
	psd_monto_descuento_propuesto_ma,
	psd_monto_neto_propuesto_ml,
	psd_monto_neto_propuesto_ma,
	psd_estatus,
	psd_agregado_usuario,
	psd_observaciones_rf,
	smn_rol_id,
	psd_idioma,
	psd_usuario,
	psd_fecha_registro,
	psd_hora,
	smn_ingresos_id,
	smn_recipe_medico_id
)
VALUES
(
	${seq:nextval@smn_salud.seq_smn_prestacion_servicio_medico_detalle},
	${fld:smn_prestacion_servicio_medico_cabecera_id},
	0,
	${fld:smn_ingreso_id},
	(select smn_base.smn_rel_servicio_area_unidad.smn_unidades_servicios_rf from smn_base.smn_rel_servicio_area_unidad where smn_base.smn_rel_servicio_area_unidad.smn_servicios_id=(select smn_salud.smn_documento.smn_servicio_med_rf from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id=${fld:smn_documento_id})),
	(select smn_base.smn_almacen.smn_almacen_id from smn_base.smn_almacen where smn_base.smn_almacen.alm_unidad_servicio=(select smn_base.smn_rel_servicio_area_unidad.smn_unidades_servicios_rf from smn_base.smn_rel_servicio_area_unidad where smn_base.smn_rel_servicio_area_unidad.smn_servicios_id=(select smn_salud.smn_documento.smn_servicio_med_rf from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id=${fld:smn_documento_id}))),
	(select smn_salud.smn_documento.smn_servicio_med_rf from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id=${fld:smn_documento_id}),
	'IT',
	0,
	${fld:smn_principio_activo_rf},
	0,
	${fld:rmd_dosis},
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	'RE',
	0,
	${fld:rmd_observacion},
	0,
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:smn_ingreso_id},
	${fld:smn_recipe_medico_id}
) RETURNING ${fld:smn_ingreso_id} as smn_ingreso_id, ${fld:smn_documento_id} as smn_documento_id, ${fld:smn_recipe_medico_id} as smn_recipe_medico_id, ${fld:smn_prestador_servicio_rf} as smn_prestador_servicio_rf, ${fld:rmd_dosis} as rmd_dosis;

