select
	${field}
from
	smn_salud.smn_campos_visualizacion_monitores_dispositivos
where
		smn_salud.smn_campos_visualizacion_monitores_dispositivos.smn_campos_visualizacion_monitores_dispositivos_id is not null
