INSERT INTO smn_comercial.smn_pedido_detalle
(
	smn_pedido_detalle_id,
	smn_pedido_cabecera_id,
	smn_mov_caja_cabecera_id,
	pde_naturaleza,
	smn_servicios_rf,
	smn_item_rf,
	smn_activo_fijo_rf,
	pde_cantidad_oferta,
	pde_cantidad_pedido,
	pde_cantidad_aprobada,
	pde_precio,
	pde_monto,
	smn_moneda_rf,
	smn_tasa_rf,
	pde_precio_moneda_alterna,
	pde_monto_moneda_alterna,
	pde_fecha_requerida,
	pde_estatus,
	pde_idioma,
	pde_usuario,
	pde_fecha_registro,
	pde_hora,
	smn_id_movimiento_origen
)
VALUES
(
	${seq:nextval@smn_comercial.seq_smn_pedido_detalle},
	${fld:smn_pedido_cabecera_id},
	${fld:smn_mov_caja_cabecera_id},
	'SE',	
	(case when ${fld:smn_servicios_rf} is null then 0 else ${fld:smn_servicios_rf} end),
	0,
	0,
	0,
	0,
	1,
	${fld:smn_precio_ml},
	${fld:smn_precio_ml},
	(select smn_base.smn_tasas_de_cambio.smn_monedas_id from smn_base.smn_tasas_de_cambio where smn_base.smn_tasas_de_cambio.tca_fecha_vigencia=CURRENT_DATE and smn_base.smn_tasas_de_cambio.tca_tipo_tasa=(select smn_salud.smn_documento.tca_tipo_tasa from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id = (select smn_salud.smn_ingresos.smn_documento_id from smn_salud.smn_ingresos where smn_salud.smn_ingresos.smn_ingresos_id=${fld:smn_ingreso_id}))),
	(select smn_base.smn_tasas_de_cambio.smn_tasas_de_cambio_id from smn_base.smn_tasas_de_cambio where smn_base.smn_tasas_de_cambio.tca_fecha_vigencia=CURRENT_DATE and smn_base.smn_tasas_de_cambio.tca_tipo_tasa=(select smn_salud.smn_documento.tca_tipo_tasa from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id = (select smn_salud.smn_ingresos.smn_documento_id from smn_salud.smn_ingresos where smn_salud.smn_ingresos.smn_ingresos_id=${fld:smn_ingreso_id})) LIMIT 1),
	${fld:smn_precio_ma},
	${fld:smn_precio_ma},
	'${def:date}',
	'NP',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:smn_ordenes_medicas_id}
) RETURNING smn_pedido_detalle_id, smn_servicios_rf, ${fld:smn_pedido_cabecera_id} as smn_pedido_cabecera_id, ${fld:ingresoid} as ingresoid, ${fld:smn_ordenes_medicas_id} as smn_ordenes_medicas_id;
