select DISTINCT
		smn_salud.smn_prestacion_servicio_medico_detalle.smn_prestacion_servicio_medico_detalle_id,
	smn_salud.smn_prestacion_servicio_medico_detalle.smn_prestacion_servicio_medico_cabecera_id,
	smn_salud.smn_prestacion_servicio_medico_detalle.smn_mov_caja_detalle_id,
	smn_salud.smn_prestacion_servicio_medico_detalle.smn_ingresos_mov_id as mov_id,
	smn_salud.smn_ingresos.smn_documento_id as documento,
	smn_salud.smn_ingresos.smn_ingresos_id as ingreso,
	smn_salud.smn_prestacion_servicio_medico_detalle.smn_unidades_servicios_rf,
	smn_salud.smn_prestacion_servicio_medico_detalle.smn_servicios_rf,
	smn_salud.smn_prestacion_servicio_medico_detalle.smn_componentes_rf,
	smn_salud.smn_prestacion_servicio_medico_detalle.psd_monto_propuesto_ml as nrs_monto_saldo_ml,
	smn_salud.smn_prestacion_servicio_medico_detalle.psd_monto_propuesto_ma as nrs_monto_saldo_ma,
	smn_salud.smn_prestacion_servicio_medico_detalle.psd_monto_propuesto_ml as nrs_monto_ml,
	smn_salud.smn_prestacion_servicio_medico_detalle.psd_monto_propuesto_ma as nrs_monto_ma,
	smn_salud.smn_prestacion_servicio_medico_detalle.smn_prestador_servicio_rf as smn_proveedor_id
	
from
	smn_salud.smn_prestacion_servicio_medico_detalle
	inner join smn_salud.smn_prestacion_servicio_medico_cabecera on smn_salud.smn_prestacion_servicio_medico_cabecera.smn_prestacion_servicio_medico_cabecera_id = smn_salud.smn_prestacion_servicio_medico_detalle.smn_prestacion_servicio_medico_cabecera_id
	inner join smn_salud.smn_ingresos on smn_salud.smn_ingresos.smn_ingresos_id = smn_salud.smn_prestacion_servicio_medico_cabecera.smn_ingresos_id
	inner join smn_salud.smn_ingreso_movimiento on smn_salud.smn_ingreso_movimiento.smn_ingreso_id = smn_salud.smn_ingresos.smn_ingresos_id
	left join smn_base.smn_auxiliar on smn_base.smn_auxiliar.smn_auxiliar_id = smn_salud.smn_prestacion_servicio_medico_detalle.smn_prestador_servicio_rf
	left join smn_base.smn_prestadores_servicios on smn_base.smn_prestadores_servicios.prs_auxiliar = smn_salud.smn_prestacion_servicio_medico_detalle.smn_prestador_servicio_rf
where
	smn_salud.smn_prestacion_servicio_medico_detalle.psd_tipo_componentes='HO' and
	smn_salud.smn_prestacion_servicio_medico_detalle.smn_prestacion_servicio_medico_cabecera_id = ${fld:id_prestacion}