select
	smn_prestacion_servicio_medico_cabecera_id	
from 
	smn_salud.smn_prestacion_servicio_medico_cabecera
where
	smn_prestacion_servicio_medico_cabecera_id = ${fld:smn_prestacion_servicio_medico_cabecera_id}
	