INSERT INTO smn_salud.smn_rol
(
	smn_rol_id,
	smn_usuario_id,
	rol_tipo,
	smn_corporacion_rf,
	smn_entidad_rf,
	smn_sucursal_rf,
	smn_area_servicio_rf,
	smn_unidad_servicio_rf,
	smn_estructura_organizacional_rf,
	rol_idioma,
	rol_usuario_id,
	rol_fecha_registro,
	rol_hora
)
VALUES
(
	${seq:currval@smn_salud.seq_smn_rol},
	${fld:smn_usuario_id},
	${fld:rol_tipo},
	${fld:smn_corporacion_rf},
	${fld:smn_entidad_rf},
	${fld:smn_sucursal_rf},
	${fld:smn_area_servicio_rf},
	${fld:smn_unidad_servicio_rf},
	${fld:smn_estructura_organizacional_rf},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
