INSERT INTO smn_compras.smn_requisicion_detalle (
	smn_requisicion_detalle_id,
	smn_requisicion_cabecera_id,
	smn_linea_id,
	smn_naturaleza_id,
	smn_servicio_id,
	smn_item_id,
	rrs_producto_encontrado,
	rss_cantidad,
	rrs_precio,
	rrs_monto,
	smn_moneda_id,
	rrs_precio_moneda_alterna,
	rrs_monto_moneda_alterna,
	rrs_fecha_de_requerido,
	rrs_idioma,
 	rrs_usuario,
	rrs_fecha_registro,
	rrs_hora
)VALUES(
	nextval('smn_compras.seq_smn_requisicion_detalle'),
	(select smn_compras.smn_requisicion_cabecera.smn_requisicion_cabecera_id from smn_compras.smn_requisicion_cabecera where smn_compras.smn_requisicion_cabecera.igs_doc_origen = ${fld:smn_presupuesto_id}),
	(select case when smn_compras.smn_rel_linea_item.smn_lineas_id IS NULL then 0 else smn_compras.smn_rel_linea_item.smn_lineas_id end as smn_linea_id from smn_compras.smn_rel_linea_item where smn_compras.smn_rel_linea_item.smn_item_id=${fld:smn_item_rf}),
	'IT',
	0,
	${fld:smn_item_rf},
	'SI',
	${fld:prd_cantidad},
	${fld:prd_precio},
	${fld:prd_monto_moneda_local},
	${fld:smn_moneda_rf},
	${fld:prd_precio_ma},
	${fld:prd_moneda_alterna},
	{d '${def:date}'},  
	'${def:locale}',
    '${def:user}',
    {d '${def:date}'},
    '${def:time}'
);

