INSERT INTO smn_salud.smn_prestacion_servicio_medico_detalle
(
	smn_prestacion_servicio_medico_detalle_id,
	smn_prestacion_servicio_medico_cabecera_id,
	smn_ingresos_mov_id,
	smn_unidades_servicios_rf,
	smn_servicios_rf,
	psd_tipo_componentes,
	smn_componentes_rf,
	smn_item_rf,
	smn_prestador_servicio_rf,
	psd_cantidad,
	psd_precio_propuesto_ml,
	psd_monto_propuesto_ml,
	smn_descuento_ml_rf,
	smn_moneda_rf,
	psd_precio_propuesto_ma,
	psd_monto_propuesto_ma,
	psd_monto_descuento_propuesto_ml,
	psd_monto_descuento_propuesto_ma,
	psd_monto_neto_propuesto_ml,
	psd_monto_neto_propuesto_ma,
	psd_estatus,
	psd_idioma,
	psd_usuario,
	psd_fecha_registro,
	psd_hora,
	smn_ingresos_id
)
VALUES
(
	${seq:nextval@smn_salud.seq_smn_prestacion_servicio_medico_detalle},
	(select smn_salud.smn_prestacion_servicio_medico_cabecera.smn_prestacion_servicio_medico_cabecera_id from smn_salud.smn_prestacion_servicio_medico_cabecera
where smn_salud.smn_prestacion_servicio_medico_cabecera.smn_ingresos_id=(select smn_salud.smn_presupuesto.smn_ingresos_id from smn_salud.smn_presupuesto where smn_salud.smn_presupuesto.smn_presupuesto_id=${fld:smn_presupuesto_id}) and smn_salud.smn_prestacion_servicio_medico_cabecera.smn_unidades_servicios_rf=(select smn_base.smn_grupos_prestadores.gpp_unidad_servicio from smn_base.smn_grupos_prestadores where smn_base.smn_grupos_prestadores.smn_grupos_prestadores_id=${fld:smn_grupo_prestador_rf})),
 	0,
	(select smn_base.smn_rel_servicio_area_unidad.smn_unidades_servicios_rf from smn_base.smn_rel_servicio_area_unidad where smn_base.smn_rel_servicio_area_unidad.smn_servicios_id = ${fld:smn_servicios_rf}),
	${fld:smn_servicios_rf},
	${fld:smn_tipo_componentes_rf},
	${fld:smn_componentes_rf},
	${fld:smn_item_rf},
	${fld:smn_prestadores_servicios_rf},
	${fld:prd_cantidad},
	${fld:prd_precio},
	${fld:prd_monto_moneda_local},
	${fld:prd_monto_descuento_ml},
	${fld:smn_moneda_rf},
	${fld:prd_precio_ma},
	${fld:prd_moneda_alterna},
	${fld:prd_monto_descuento_ml},
	${fld:prd_monto_descuento_ma},
	${fld:prd_monto_neto_ml},
	${fld:prd_monto_neto_ma},
	'RE',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	(select smn_salud.smn_presupuesto.smn_ingresos_id from smn_salud.smn_presupuesto where smn_salud.smn_presupuesto.smn_presupuesto_id=${fld:smn_presupuesto_id} limit 1)

);
