select * from smn_salud.smn_rel_solicitud_pre_patologias
inner join smn_salud.smn_patologia on smn_salud.smn_patologia.smn_patologia_id = smn_salud.smn_rel_solicitud_pre_patologias.smn_patologias_id
inner join smn_salud.smn_solicitud_presupuesto on smn_salud.smn_solicitud_presupuesto.smn_solicitud_presupuesto_id = smn_salud.smn_rel_solicitud_pre_patologias.smn_solicitud_presupuesto_id
WHERE smn_salud.smn_rel_solicitud_pre_patologias.smn_solicitud_presupuesto_id = ${fld:id}