INSERT INTO smn_salud.smn_coberturas
(
	smn_coberturas_id,
	cob_codigo,
	cob_descripcion,
	cob_tiempo_servicio,
	cob_unidad_tiempo_rf,
	cob_deducible,
	cob_otros_centros,
	cob_cantidad_servicio,
	cob_cobertura_desde,
	cob_cobertura_hasta,
	cob_porc_deducible,
	cob_idioma,
	cob_usuario,
	cob_fecha_registro,
	cob_hora,
	smn_tipo_coberturas_id
)
VALUES
(
	${seq:currval@smn_salud.seq_smn_coberturas},
	${fld:cob_codigo},
	${fld:cob_descripcion},
	${fld:cob_tiempo_servicio},
	${fld:cob_unidad_tiempo_rf},
	${fld:cob_deducible},
	${fld:cob_otros_centros},
	${fld:cob_cantidad_servicio},
	${fld:cob_cobertura_desde},
	${fld:cob_cobertura_hasta},
	${fld:cob_porc_deducible},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:smn_tipo_coberturas_id}
)
