INSERT INTO smn_comercial.smn_pedido_componentes
(
	smn_pedido_componentes_id,
	smn_pedido_detalle_id,
	smn_mov_caja_detalle_id,
	smn_ingresos_rf,
	smn_pedido_cabecera_id,
	smn_grupo_componente_rf,
	pco_tipo_componente,
	smn_componente_rf,
	pco_es_prestador_servicio,
	smn_clase_auxiliar_rf,
	smn_auxiliar_rf,
	pco_naturaleza,
	smn_item_rf,
	smn_servicio_rf,
	pco_cantidad,
	smn_precio_ml_rf,
	pco_monto_ml,
	smn_moneda_rf,
	smn_tasa_rf,
	smn_precio_ma,
	smn_monto_ma,
	pco_imprime,
	smn_grupo_titulo_impresion_rf,
	smn_tipo_gasto_rf,
	smn_sub_tipo_gasto_rf,
	pco_estatus,
	pco_idioma,
	pco_usuario,
	pco_fecha_registro,
	pco_hora,
	smn_prestador_servicio_rf,
	pco_tipo_acumulado
)
VALUES
(
	${seq:nextval@smn_comercial.seq_smn_pedido_componentes},
	${fld:smn_pedido_detalle_id},
	0,
	(select smn_salud.smn_ingresos.igs_num_ingreso from smn_salud.smn_ingresos where smn_salud.smn_ingresos.smn_ingresos_id=${fld:ingresoid} limit 1),
	${fld:smn_pedido_cabecera_id},
	0,
	${fld:psd_tipo_componentes},
	${fld:smn_componentes_rf},
	0,
	(select case WHEN smn_base.smn_prestadores_servicios.prs_clase_auxiliar is null then 0 else smn_base.smn_prestadores_servicios.prs_clase_auxiliar end as prs_clase_auxiliar from smn_base.smn_prestadores_servicios where smn_base.smn_prestadores_servicios.smn_prestadores_servicios_id=(SELECT smn_salud.smn_prestacion_servicio_medico_cabecera.smn_prestador_servicio_rf FROM smn_salud.smn_prestacion_servicio_medico_cabecera where smn_salud.smn_prestacion_servicio_medico_cabecera.smn_ingresos_id=${fld:ingresoid} limit 1) limit 1),
	(select case WHEN smn_base.smn_prestadores_servicios.prs_auxiliar is null then 0 else smn_base.smn_prestadores_servicios.prs_auxiliar end as prs_auxiliar from smn_base.smn_prestadores_servicios where smn_base.smn_prestadores_servicios.smn_prestadores_servicios_id=(SELECT smn_salud.smn_prestacion_servicio_medico_cabecera.smn_prestador_servicio_rf FROM smn_salud.smn_prestacion_servicio_medico_cabecera where smn_salud.smn_prestacion_servicio_medico_cabecera.smn_ingresos_id=${fld:ingresoid} limit 1) limit 1),
	${fld:psd_tipo_componentes},
	${fld:smn_item_rf},
	${fld:smn_servicios_rf},
	1,
	${fld:smn_precio_ml},
	${fld:psd_cantidad}*${fld:smn_precio_ml},
	${fld:smn_moneda_rf},
	(select smn_base.smn_tasas_de_cambio.smn_tasas_de_cambio_id from smn_base.smn_tasas_de_cambio where smn_base.smn_tasas_de_cambio.tca_fecha_vigencia=CURRENT_DATE and smn_base.smn_tasas_de_cambio.tca_tipo_tasa=(select smn_salud.smn_documento.tca_tipo_tasa from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id = (select smn_salud.smn_ingresos.smn_documento_id from smn_salud.smn_ingresos where smn_salud.smn_ingresos.smn_ingresos_id=${fld:ingresoid}))),
	${fld:smn_precio_ma},
    ${fld:psd_cantidad}*${fld:smn_precio_ma},
	'S',
	(select smn_base.smn_componentes.smn_grupo_titulo_impresion_rf from smn_base.smn_componentes where smn_base.smn_componentes.smn_componentes_id=${fld:smn_componentes_rf}),
	0,
	0,
	'GE',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:smn_prestador_servicio_rf},
	(select smn_base.smn_componentes.cmp_acumula_servicio from smn_base.smn_componentes where smn_base.smn_componentes.smn_componentes_id=${fld:smn_componentes_rf})
) ;