SELECT 
smn_base.smn_auxiliar_unidades_servicios.smn_auxiliar_unidades_servicios_id as id,
smn_base.smn_auxiliar_unidades_servicios.tns_codigo ||'-'||smn_base.smn_auxiliar_unidades_servicios.tns_descripcion as item 
from smn_base.smn_auxiliar_areas_servicios, smn_base.smn_auxiliar_unidades_servicios
where smn_base.smn_auxiliar_unidades_servicios.smn_auxiliar_areas_servicios_id=(SELECT smn_base.smn_auxiliar_areas_servicios.smn_auxiliar_areas_servicios_id
from smn_base.smn_auxiliar_areas_servicios
WHERE upper(smn_base.smn_auxiliar_areas_servicios.tse_descripcion)=upper(${fld:id})) GROUP BY id