select
		smn_salud.smn_solicitud_presupuesto.spr_solicitud,
	smn_salud.smn_solicitud_presupuesto.smn_auxiliar,
	smn_salud.smn_solicitud_presupuesto.smn_contratante_id,
	smn_salud.smn_solicitud_presupuesto.smn_patologia_id,
	smn_salud.smn_solicitud_presupuesto.spr_dias_hospitalizacion,
	smn_salud.smn_solicitud_presupuesto.spr_instrumentales,
	smn_salud.smn_solicitud_presupuesto.spr_honorarios,
	smn_salud.smn_solicitud_presupuesto.spr_estatus,
	smn_salud.smn_solicitud_presupuesto.spr_fecha_registro
from
	smn_salud.smn_solicitud_presupuesto 
where
	smn_salud.smn_solicitud_presupuesto.smn_solicitud_presupuesto_id = ${fld:id}
