select
		smn_salud.smn_prestacion_servicio_medico_cabecera.smn_ingresos_id,
	smn_salud.smn_prestacion_servicio_medico_cabecera.smn_mov_caja_cabecera_id,
	smn_salud.smn_prestacion_servicio_medico_cabecera.smn_unidades_servicios_rf,
	smn_salud.smn_prestacion_servicio_medico_cabecera.psc_estatus,
	smn_salud.smn_prestacion_servicio_medico_cabecera.psc_fecha_registro
from
	smn_salud.smn_prestacion_servicio_medico_cabecera 
where
	smn_salud.smn_prestacion_servicio_medico_cabecera.smn_prestacion_servicio_medico_cabecera_id = ${fld:id}
