select
		smn_salud.smn_rel_patologia_servicios.smn_rel_patologia_servicios_id,
	smn_salud.smn_patologia.smn_patologia_id,
	smn_salud.smn_patologia.pat_codigo as pat_codigo_pl0,
select
		smn_salud.smn_rel_patologia_servicios.smn_rel_patologia_servicios_id,
select
		smn_salud.smn_rel_patologia_servicios.smn_rel_patologia_servicios_id,
	smn_salud.smn_rel_patologia_servicios.smn_patologia_id,
	smn_salud.smn_rel_patologia_servicios.smn_servicio_rf,
	smn_salud.smn_rel_patologia_servicios.rps_cantidad,
	smn_salud.smn_rel_patologia_servicios.rps_fecha_registro
	
from
	smn_salud.smn_patologia,
	smn_salud.smn_rel_patologia_servicios
where
	smn_salud.smn_patologia.smn_patologia_id=smn_salud.smn_rel_patologia_servicios.smn_patologia_id
