select
		smn_salud.smn_rel_control_quirofano_prestador.smn_rel_control_quirofano_prestador_id,
select
		smn_salud.smn_rel_control_quirofano_prestador.smn_rel_control_quirofano_prestador_id,
select
		smn_salud.smn_rel_control_quirofano_prestador.smn_rel_control_quirofano_prestador_id,
select
		smn_salud.smn_rel_control_quirofano_prestador.smn_rel_control_quirofano_prestador_id,
select
		smn_salud.smn_rel_control_quirofano_prestador.smn_rel_control_quirofano_prestador_id,
	smn_salud.smn_rel_control_quirofano_prestador.smn_control_quirofano_id,
	smn_salud.smn_rel_control_quirofano_prestador.smn_servicios_rf,
	smn_salud.smn_rel_control_quirofano_prestador.smn_componente_rf,
	smn_salud.smn_rel_control_quirofano_prestador.smn_grupo_prestador_servicio_rf,
	smn_salud.smn_rel_control_quirofano_prestador.smn_prestador_servicio_rf
	
from
	smn_salud.smn_rel_control_quirofano_prestador
