INSERT INTO smn_salud.smn_presupuesto
(
	smn_presupuesto_id,
	pre_numero_control,
	pre_fecha,
	pre_titular,
	pre_beneficiario,
	pre_plan,
	pre_clase_auxiliar,
	pre_auxiliar,
	pre_vigencia_hasta,
	smn_ordenes_medicas_id,
	smn_estado_presupuesto_id,
	pre_idioma,
	pre_usuario,
	pre_fecha_registro,
	pre_hora
)
VALUES
(
	${seq:currval@smn_salud.seq_smn_presupuesto},
	${fld:pre_numero_control},
	${fld:pre_fecha},
	${fld:pre_titular},
	${fld:pre_beneficiario},
	${fld:pre_plan},
	${fld:pre_clase_auxiliar},
	${fld:pre_auxiliar},
	${fld:pre_vigencia_hasta},
	${fld:smn_ordenes_medicas_id},
	${fld:smn_estado_presupuesto_id},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
