SELECT DISTINCT
smn_base.smn_grupos_prestadores.smn_grupos_prestadores_id as id, smn_base.smn_grupos_prestadores.gpp_descripcion as item
FROM
smn_base.smn_agenda
INNER JOIN smn_salud.smn_agenda_medica ON smn_base.smn_agenda.smn_agenda_id = smn_salud.smn_agenda_medica.smn_agenda_id
INNER JOIN smn_base.smn_grupo_prestador_servicio_frecuencia ON smn_salud.smn_agenda_medica.smn_grupo_prestador_servicio_rf = smn_base.smn_grupo_prestador_servicio_frecuencia.smn_grupos_prestadores_id
inner join smn_base.smn_grupos_prestadores on  smn_base.smn_grupos_prestadores.smn_grupos_prestadores_id = smn_base.smn_grupo_prestador_servicio_frecuencia.smn_grupos_prestadores_id
WHERE
smn_base.smn_grupo_prestador_servicio_frecuencia.smn_servicios_id =${fld:id}