INSERT INTO smn_salud.smn_ingreso_movimiento
(
	smn_ingresos_mov_id,
	smn_ingreso_id,
	smn_servicios_rf,
	smn_unidades_servicios_rf,
	smn_componente_rf,
	inm_accion,
	inm_cantidad,
	inm_precio_ml,
	inm_monto_ml,
	inm_precio_ma,
	inm_monto_ma,
	smn_moneda_rf,
	smn_tasa_rf,
	inm_monto_cobertura_contratante,
	inm_monto_cobertura_paciente,
	smn_tipo_consulta_rf,
	smn_grupo_prestador_servicio_rf,
	smn_prestador_servicio_rf,
	smn_motivos_id,
	smn_clase_auxiliar_rf,
	smn_auxiliar_rf,
	inm_ordenante_descripcion,
	smn_sintoma_id,
	inm_tipo_orden,
	inm_num_orden_medica,
	inm_estatus,
	inm_idioma,
	inm_usuario,
	inm_fecha_registro,
	inm_hora
)
VALUES
(
	${seq:nextval@smn_salud.seq_smn_ingreso_movimiento},
	${fld:smn_ingreso_id},
	(select smn_salud.smn_documento.smn_servicio_med_rf from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id=${fld:smn_documento_id}),
	(select smn_base.smn_rel_servicio_area_unidad.smn_unidades_servicios_rf from smn_base.smn_rel_servicio_area_unidad where smn_base.smn_rel_servicio_area_unidad.smn_servicios_id=(select smn_salud.smn_documento.smn_servicio_med_rf from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id=${fld:smn_documento_id})),
	(select smn_base.smn_servicios_componentes.smn_componentes_id from smn_base.smn_servicios_componentes inner join smn_base.smn_componentes on smn_base.smn_componentes.smn_componentes_id = smn_base.smn_servicios_componentes.smn_componentes_id 
where smn_base.smn_servicios_componentes.smn_servicios_id=(select smn_salud.smn_documento.smn_servicio_med_rf from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id=${fld:smn_documento_id}) order by smn_base.smn_componentes.smn_componentes_id asc limit 1),
	'RECIPE MEDICO',
	${fld:rmd_dosis},
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	(select smn_base.smn_servicios.smn_clase_auxiliar_rf  as grupo_prestador from smn_base.smn_servicios where smn_base.smn_servicios.smn_servicios_id = (select smn_salud.smn_documento.smn_servicio_med_rf from smn_salud.smn_documento where smn_salud.smn_documento.smn_documento_id=${fld:smn_documento_id})),
	0,
	0,
	0,
	0,
	${fld:smn_prestador_servicio_rf},
	0,
	'CO',
	${fld:smn_recipe_medico_id},
	'AC',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
